# Decision Tree

In [1]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier

/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [4]:
iris = datasets.load_iris()
X = iris.data[:, 2:]
y = iris.target

In [5]:
X.shape, y.shape

((150, 2), (150,))

In [6]:
tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

**Virsualization**

In [8]:
from sklearn.tree import export_graphviz

In [11]:
export_graphviz(tree_clf, out_file=open('iris_tree.dot', 'w+'),
               feature_names=iris.feature_names[2:],
               class_names=iris.target_names,
               rounded=True,
               filled=True)

In [14]:
# dot -Tpng iris_tree.dot -o iris_tree.png

![](iris_tree.png)

In [16]:
tree_clf.predict_proba([[5, 1.5]])

array([[0.        , 0.90740741, 0.09259259]])

In [17]:
tree_clf.predict([[5, 1.5]])

array([1])

In [18]:
tree_clf.classes_

array([0, 1, 2])