# Getting Started

## Tensors

Tensors are similar to Numpy's ndarray, with the addition being that Tensors can also be used on GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matri, unitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 1.5846e+29, 2.7448e+25],
        [2.0005e+00, 1.8361e+25, 1.4603e-19],
        [6.4069e+02, 2.7489e+20, 1.5444e+25],
        [1.6217e-19, 7.0062e+22, 1.6795e+08],
        [4.7423e+30, 4.7393e+30, 9.5461e-01]])


Construct a randomly initialized matrix:

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8428, 0.5853, 0.1359],
        [0.7969, 0.7075, 0.9140],
        [0.4521, 0.6253, 0.1270],
        [0.7486, 0.9715, 0.0493],
        [0.5000, 0.1232, 0.1149]])


Construct a tensor directly from data:

In [4]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. 

In [5]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5029, -0.9651,  0.8417],
        [ 0.4836,  0.7376,  0.9555],
        [-0.8159, -1.3198, -0.0644],
        [-0.4211,  0.7990,  0.6569],
        [-0.1072,  1.6665, -1.2108]])


Get its size:

In [6]:
print(x.size())

torch.Size([5, 3])


> `torch.Size` is in fact a tuple, so it supports all tuple of operations.

## Operations

In [7]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.9430, -0.2668,  0.9686],
        [ 0.9783,  1.0733,  1.3281],
        [-0.6967, -0.4507,  0.4355],
        [-0.2473,  1.6276,  1.4904],
        [ 0.7400,  2.1859, -0.6935]])


In [8]:
print(torch.add(x, y))

tensor([[ 0.9430, -0.2668,  0.9686],
        [ 0.9783,  1.0733,  1.3281],
        [-0.6967, -0.4507,  0.4355],
        [-0.2473,  1.6276,  1.4904],
        [ 0.7400,  2.1859, -0.6935]])


In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.9430, -0.2668,  0.9686],
        [ 0.9783,  1.0733,  1.3281],
        [-0.6967, -0.4507,  0.4355],
        [-0.2473,  1.6276,  1.4904],
        [ 0.7400,  2.1859, -0.6935]])


in-place:

In [10]:
y.add_(x)
print(y)

tensor([[ 0.9430, -0.2668,  0.9686],
        [ 0.9783,  1.0733,  1.3281],
        [-0.6967, -0.4507,  0.4355],
        [-0.2473,  1.6276,  1.4904],
        [ 0.7400,  2.1859, -0.6935]])


In [11]:
print(x[:, 1])

tensor([-0.9651,  0.7376, -1.3198,  0.7990,  1.6665])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [12]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have one element tensor, use `.item()` to get the value as a Python number

In [13]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.7051])
-1.7051204442977905


## Numpy Bridge

The Torch Tensor and Numpy array share their underlying memory locations(if the Torch Tensor is on CPU), ang changing one will change the other.

### Converting a Torch Tensor to a Numpy Array

In [14]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [15]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [16]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy Array to Torch Tensro

In [17]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
