# Getting Started

## Tensors

Tensors are similar to Numpy's ndarray, with the addition being that Tensors can also be used on GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matri, unitialized:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  7.2387e-19],
        [-1.0845e-19,  1.1210e-44,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


Construct a randomly initialized matrix:

In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8261, 0.7564, 0.1643],
        [0.0453, 0.8668, 0.5865],
        [0.0073, 0.5496, 0.6527],
        [0.5789, 0.8891, 0.9867],
        [0.1830, 0.8715, 0.8158]])


Construct a tensor directly from data:

In [9]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. 

In [12]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.2096, -1.3380, -1.5150],
        [-0.7582, -1.9592,  0.9482],
        [-0.0549, -0.8415, -0.3877],
        [ 0.0795, -0.6163,  1.3443],
        [-0.8869,  0.3876,  1.2309]])


Get its size:

In [13]:
print(x.size())

torch.Size([5, 3])


> `torch.Size` is in fact a tuple, so it supports all tuple of operations.

## Operations

In [20]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 2.2693, -0.7715, -0.5796],
        [-0.0661, -1.7735,  1.4615],
        [ 0.8317,  0.0729, -0.0342],
        [ 0.9624, -0.0792,  1.8395],
        [-0.3541,  0.4819,  1.8483]])


In [16]:
print(torch.add(x, y))

tensor([[ 2.8693, -0.8527, -0.9749],
        [-0.4008, -1.7220,  1.3396],
        [ 0.4367, -0.7745,  0.2473],
        [ 1.0753, -0.3531,  1.4374],
        [-0.4286,  0.6155,  1.7803]])


In [17]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.8693, -0.8527, -0.9749],
        [-0.4008, -1.7220,  1.3396],
        [ 0.4367, -0.7745,  0.2473],
        [ 1.0753, -0.3531,  1.4374],
        [-0.4286,  0.6155,  1.7803]])


in-place:

In [21]:
y.add_(x)
print(y)

tensor([[ 2.2693, -0.7715, -0.5796],
        [-0.0661, -1.7735,  1.4615],
        [ 0.8317,  0.0729, -0.0342],
        [ 0.9624, -0.0792,  1.8395],
        [-0.3541,  0.4819,  1.8483]])


In [3]:
print(x[:, 1])

tensor([-4.6566e-10,  1.1210e-44,  0.0000e+00,  0.0000e+00,  0.0000e+00])


Resizing: If you want to resize/reshape tensor, you can use `torch.view`:

In [4]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8) # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have one element tensor, use `.item()` to get the value as a Python number

In [28]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7568])
0.7568413019180298


## Numpy Bridge

The Torch Tensor and Numpy array share their underlying memory locations(if the Torch Tensor is on CPU), ang changing one will change the other.

### Converting a Torch Tensor to a Numpy Array

In [29]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting Numpy Array to Torch Tensro

In [35]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
