# Tensor sigmoid后转化成二元值

In [1]:
import torch
import torch.nn.functional as F

In [2]:
t = torch.randn(5, 4)

In [3]:
t

tensor([[-0.0955, -0.6786,  0.6100,  1.0872],
        [ 0.0155, -1.1633, -0.3528, -1.5430],
        [ 0.6666,  0.2279, -1.8384,  0.9682],
        [-0.7140, -0.0777,  0.3042, -0.7632],
        [ 0.0788, -0.0043,  1.4602, -0.4117]])

In [4]:
t_sigmoid = torch.sigmoid(t)

In [5]:
t_sigmoid

tensor([[0.4761, 0.3366, 0.6480, 0.7479],
        [0.5039, 0.2381, 0.4127, 0.1761],
        [0.6607, 0.5567, 0.1372, 0.7248],
        [0.3287, 0.4806, 0.5755, 0.3179],
        [0.5197, 0.4989, 0.8116, 0.3985]])

In [6]:
t_sigmoid[t_sigmoid >= torch.tensor(0.5)] = 1
t_sigmoid[t_sigmoid < torch.tensor(0.5)] = 0

In [7]:
t_sigmoid

tensor([[0., 0., 1., 1.],
        [1., 0., 0., 0.],
        [1., 1., 0., 1.],
        [0., 0., 1., 0.],
        [1., 0., 1., 0.]])