# torch.Tensor

In [4]:
import torch
import numpy as np
import pandas as pd

`torch.Tensor` is multi-dimensional matrix containing elements of a single data type.

Torch define nine CPU tensor type and nine GPU tensor type.

`torch.Tensor` is an alias for the default tensor type(`torch.FloatTensor`).

A tensor can be construct from a Python `list` or sequence using `torch.tensor()` constructor.

In [3]:
torch.tensor([[1, -1], [1, 1]])

tensor([[ 1, -1],
        [ 1,  1]])

In [5]:
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

> `torch.tensor()` always copies `data`. If you have a Tensor data and jsut want to change its `requires_grad` flag, use `requires_grad_()` or `detach()` to avoid a copy. If you have a nupy array and want to avoid a copy, use `torch.as_tensor()`.

 A tensor of specific data type can be constructed by passing a `torch.dtype` and/or a `torch.device` to a constructor or tensor creation op:

In [6]:
torch.zeros(2, 3, dtype=torch.float32)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

The contents of a tensor can be accessed and modified using Python's indexing and slicing notation:

In [15]:
x = torch.as_tensor(np.arange(1, 7).reshape(2, 3))
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
x[1][2]

tensor(6)

In [17]:
x[0][1] = 8

In [18]:
x

tensor([[1, 8, 3],
        [4, 5, 6]])

Use `torch.Tensor.item()` to get a Python number from a tensor containing a single value:

In [28]:
x = torch.tensor([[1]])

In [29]:
x.item()

1

In [31]:
x = torch.tensor(2)

In [32]:
x.item()

2

A tensor can be created with `requies_grad=True` so that `torch.autograd` records operations on them for automatic differention.

In [38]:
x = torch.tensor([[1, -1], [1, 1]], dtype=torch.float32,
                 requires_grad=True)
y = x.pow(2).sum()

In [39]:
y.backward()

In [40]:
x.grad

tensor([[ 2., -2.],
        [ 2.,  2.]])

Each tensor has an associated `torch.Storage`, which holds its data. The tensor class also provides multi-dimensional, strided view of a strorage and defines numeric operations on it.

In [50]:
tensor = torch.ones((2,), dtype=torch.int8)

In [51]:
tensor

tensor([1, 1], dtype=torch.int8)

In [55]:
data = [[0, 1], [2, 3]]
tensor.new_tensor(data)

tensor([[0, 1],
        [2, 3]], dtype=torch.int8)

In [54]:
tensor

tensor([1, 1], dtype=torch.int8)

In [57]:
tensor.detach?