NumPy广播机制

**References:**
   
* *Python-Data-Science-Handbook.pdf*

**Visualization of NumPy broadcasting**

![](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

* 规则1：如果两个数组的维度不同，那么小的维度数组的形状会在最左边补1
* 规则2：如果两个数组的形状在任何一个维度都不匹配，那么数组的形状会沿着纬度为1的维度扩展以匹配另外一个数组的形状
* 规则3：如果两个数组的形状在任何一个维度上都不匹配并且没有任何一个维度为1，那么会引发异常

**Rules of Broadcasting**

Broadcasting is NumPy follows a strict set of rules to determine the interaction between the two arrays:

* Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimension is padded with ones on its leading (left) side.
* Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal 1 in the that dimension is stretched to match the other shape.
* Rule 3: If in any dimension the size disagree and neither is equal 1, an error is raised.

**Examples**

In [1]:
import numpy as np

In [2]:
np.arange(3) + 5

array([5, 6, 7])

In [3]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [4]:
np.arange(3).reshape(3, 1) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])