# 理解PyTorch Tensor

In [1]:
import torch

In [2]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
t = t.expand(3, 2, 3)

In [3]:
t

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

In [4]:
t.shape

torch.Size([3, 2, 3])

第0维度

In [5]:
t.sum(0)

tensor([[ 3,  6,  9],
        [12, 15, 18]])

<img src="https://img.mathpretty.com/20200409_022930_ixomgr1.gif" width="200" height="200" align="center">

第1维度

In [6]:
t.sum(1)

tensor([[5, 7, 9],
        [5, 7, 9],
        [5, 7, 9]])

<img src="https://img.mathpretty.com/20200409_023117_qb6rrtg.gif" width="200" height="200" align="center">

第2维度

In [7]:
t.sum(2)

tensor([[ 6, 15],
        [ 6, 15],
        [ 6, 15]])

 <img src="https://img.mathpretty.com/20200409_023243_usk595h.gif" width = "200" height = "200" align=center />

## 参考文献

* *https://towardsdatascience.com/understanding-dimensions-in-pytorch-6edf9972d3be*
* *https://mathpretty.com/12065.html*